version: '2'
services:
    thcssondong-app:
        image: thcssondong
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://thcssondong-mysql:3306/thcssondong?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    thcssondong-mysql:
        extends:
            file: mysql.yml
            service: thcssondong-mysql
